const mockVideos = [
  // FEATURED BILLBOARD SLIDES (Netflix Carousel style)
  {
    id: "ScMzIvxBSi4",
    platform: "youtube",
    title: "Sights of Space: A Walk Outside the Space Station",
    description: "Experience the jaw-dropping beauty and terrifying vastness of space through the eyes of NASA astronauts. This curated footage captures actual spacewalks outside the International Space Station, showcasing Earth in high-definition 4K glory, the details of the orbital station, and the endless abyss of the cosmos.",
    thumbnail: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1600&q=80",
    channelName: "NASA",
    uploadDate: "2025-10-12",
    duration: "4:32",
    views: "3.4M",
    category: "Sci-Fi & Space",
    matchScore: "99% Match",
    year: "2025",
    rating: "G",
    language: "English",
    featured: true,
    slideIndex: 0
  },
  {
    id: "76979871",
    platform: "vimeo",
    title: "The Mountain - Breathtaking Landscapes of El Teide",
    description: "A jaw-dropping landscape timelapse of Spain's highest mountain, El Teide, including the Milky Way rising over volcanic peaks, ocean fog banks rolling through pine forests, and stunning cloud inversions.",
    thumbnail: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=80",
    channelName: "TS Photography",
    uploadDate: "2013-04-20",
    duration: "3:09",
    views: "2.1M",
    category: "Nature & Wildlife",
    matchScore: "96% Match",
    year: "2013",
    rating: "G",
    language: "Spanish",
    featured: true,
    slideIndex: 1
  },
  {
    id: "x2uvqby",
    platform: "dailymotion",
    title: "Space Exploration: Journey Through the Universe",
    description: "Embark on an epic journey to explore stars, nebulae, planets, and galaxies. This visual walk-through covers the fundamentals of modern cosmology and our ongoing search for active interstellar worlds.",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=80",
    channelName: "Cosmos Today",
    uploadDate: "2025-11-05",
    duration: "32:07",
    views: "120K",
    category: "Sci-Fi & Space",
    matchScore: "91% Match",
    year: "2025",
    rating: "G",
    language: "English",
    featured: true,
    slideIndex: 2
  },

  // LIVE SPORTS / CRICKET MATCH VIDEOS (Hotstar scorecards link to these!)
  {
    id: "uPH8ZgD_M1g",
    platform: "youtube",
    title: "IND vs AUS ICC Men's Cricket World Cup Highlights",
    description: "Catch all the thrilling moments, boundaries, and wickets as India locks horns with Australia in the ICC Men's T20 World Cup Super 8 clash. Relive the spectacular batting performance and nail-biting finishes.",
    thumbnail: "https://images.unsplash.com/photo-1518605125802-006dcc629439?auto=format&fit=crop&w=800&q=80",
    channelName: "Star Sports Live",
    uploadDate: "2026-06-25",
    duration: "15:45",
    views: "12M",
    category: "Live Sports",
    matchScore: "98% Match",
    year: "2026",
    rating: "G",
    language: "Hindi",
    isSports: true
  },
  {
    id: "gEPmA3pPZ84",
    platform: "youtube",
    title: "FC Barcelona vs Real Madrid - El Clásico Highlights",
    description: "The ultimate rivalry! Relive all the goals, tactical masterclasses, and drama of El Clásico as FC Barcelona clashes with Real Madrid in an electric Camp Nou stadium.",
    thumbnail: "https://images.unsplash.com/photo-1605712916066-e143c317df72?auto=format&fit=crop&w=800&q=80",
    channelName: "La Liga Official",
    uploadDate: "2026-05-18",
    duration: "10:20",
    views: "8.5M",
    category: "Live Sports",
    matchScore: "94% Match",
    year: "2026",
    rating: "G",
    language: "Spanish",
    isSports: true
  },

  // SCI-FI & SPACE ROW
  {
    id: "659357593",
    platform: "vimeo",
    title: "Earth Timelapse: A View from the ISS",
    description: "A stunning timelapse compilation of our planet Earth as seen from the International Space Station. Features lightning storms, city lights at night, and the Auroras.",
    thumbnail: "https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?auto=format&fit=crop&w=800&q=80",
    channelName: "Space Science Labs",
    uploadDate: "2026-01-20",
    duration: "3:45",
    views: "480K",
    category: "Sci-Fi & Space",
    matchScore: "95% Match",
    year: "2026",
    rating: "PG",
    language: "English"
  },
  {
    id: "dQw4w9WgXcQ",
    platform: "youtube",
    title: "Rick Astley - Never Gonna Give You Up (Official Music Video)",
    description: "The legendary, chart-topping 1987 debut single by Rick Astley. A timeless dance-pop classic that became a cornerstone of internet history.",
    thumbnail: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
    channelName: "Rick Astley",
    uploadDate: "2009-10-25",
    duration: "3:33",
    views: "1.4B",
    category: "Music & Shows",
    matchScore: "98% Match",
    year: "1987",
    rating: "G",
    language: "English"
  },
  {
    id: "FzG4uDgje3M",
    platform: "youtube",
    title: "Star Wars: The Force Awakens - Official Teaser 2",
    description: "The second teaser trailer for Star Wars: The Force Awakens. Han Solo and Chewbacca return home in this epic look at the seventh installment in the Skywalker saga.",
    thumbnail: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
    channelName: "Star Wars",
    uploadDate: "2015-04-16",
    duration: "2:00",
    views: "115M",
    category: "Sci-Fi & Space",
    matchScore: "97% Match",
    year: "2015",
    rating: "PG-13",
    language: "English"
  },

  // NATURE & WILDLIFE
  {
    id: "C3sD17H1V6k",
    platform: "youtube",
    title: "Life in the Deep Ocean (4K Underwater Footage)",
    description: "Dive deep into the twilight and midnight zones of the ocean to meet bizarre creatures. Discover glowing siphonophores, giant isopods, and the mysterious blobfish, filmed by deep-sea submersibles.",
    thumbnail: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
    channelName: "DeepSea Discover",
    uploadDate: "2025-08-30",
    duration: "11:22",
    views: "890K",
    category: "Nature & Wildlife",
    matchScore: "94% Match",
    year: "2025",
    rating: "G",
    language: "English"
  },
  {
    id: "x51xwf",
    platform: "dailymotion",
    title: "Nature, Nature, Nature! Breathtaking Wilderness",
    description: "A magnificent cinematic reportage focusing on pristine forests, mountain ranges, and bubbling wilderness streams. Observe wildlife in their untouched natural habitats.",
    thumbnail: "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=800&q=80",
    channelName: "Alpine Escapes",
    uploadDate: "2026-03-12",
    duration: "14:04",
    views: "75K",
    category: "Nature & Wildlife",
    matchScore: "92% Match",
    year: "2026",
    rating: "G",
    language: "French"
  },
  {
    id: "148281358",
    platform: "vimeo",
    title: "Forest Echoes - A Visual Journey Through Autumn",
    description: "A calming macro study of forests in autumn. Focuses on golden leaves falling, dew drops on mushrooms, and streams bubbling over stones in soft-focus closeups.",
    thumbnail: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=80",
    channelName: "CineGreen",
    uploadDate: "2025-11-20",
    duration: "4:00",
    views: "150K",
    category: "Nature & Wildlife",
    matchScore: "90% Match",
    year: "2025",
    rating: "G",
    language: "English"
  },

  // SHORT FILMS & ANIMATION
  {
    id: "1084537",
    platform: "vimeo",
    title: "Big Buck Bunny - The Landmark Open-Source Movie",
    description: "A large and lovable rabbit's day is ruined by three mischievous rodents. He decides to take his revenge in comical ways in this classic Blender open-source project.",
    thumbnail: "https://peach.blender.org/wp-content/uploads/title_anouncement.jpg",
    channelName: "Blender Foundation",
    uploadDate: "2008-04-10",
    duration: "9:56",
    views: "15M",
    category: "Short Films & Animation",
    matchScore: "93% Match",
    year: "2008",
    rating: "G",
    language: "English"
  },
  {
    id: "tgbNymZ7vqY",
    platform: "youtube",
    title: "The Muppets - Bohemian Rhapsody",
    description: "The Muppets perform Queen's Bohemian Rhapsody, featuring Gonzo, Miss Piggy, Fozzie Bear, and the rest of the gang in a musical masterpiece.",
    thumbnail: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80",
    channelName: "The Muppets",
    uploadDate: "2009-11-23",
    duration: "4:47",
    views: "112M",
    category: "Music & Shows",
    matchScore: "96% Match",
    year: "2009",
    rating: "G",
    language: "English"
  },
  {
    id: "22439234",
    platform: "vimeo",
    title: "Sintel - Blender Open Movie Project",
    description: "The story follows Sintel, a lonely girl who rescues and bonds with a baby dragon. When the dragon is kidnapped, she embarks on a dangerous journey to save him.",
    thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80",
    channelName: "Blender Foundation",
    uploadDate: "2010-09-30",
    duration: "14:48",
    views: "8.5M",
    category: "Short Films & Animation",
    matchScore: "95% Match",
    year: "2010",
    rating: "PG",
    language: "English"
  },
  {
    id: "x5c1jhy",
    platform: "dailymotion",
    title: "Artnutzz CGI Animation Portfolio Showcase",
    description: "Experience high-end CGI 3D character renders, visual effects, and classic 2D digital animations in this creative short film portfolio compilation.",
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    channelName: "CGI Shorts Hub",
    uploadDate: "2015-08-25",
    duration: "0:52",
    views: "340K",
    category: "Short Films & Animation",
    matchScore: "92% Match",
    year: "2015",
    rating: "G",
    language: "Hindi"
  },

  // ENTERTAINMENT & TECH
  {
    id: "L_LUpnjgPso",
    platform: "youtube",
    title: "Marvel's The Avengers - Official Trailer",
    description: "Superheroes from across the Marvel Cinematic Universe unite to stop Loki and his alien army from taking over planet Earth in this blockbuster trailer.",
    thumbnail: "https://images.unsplash.com/photo-1569003339405-ea396a5a8a90?auto=format&fit=crop&w=800&q=80",
    channelName: "Marvel Entertainment",
    uploadDate: "2012-02-29",
    duration: "2:23",
    views: "98M",
    category: "Music & Shows",
    matchScore: "94% Match",
    year: "2012",
    rating: "PG-13",
    language: "English"
  },
  {
    id: "x8y6xdu",
    platform: "dailymotion",
    title: "What Is Technology? Advanced Tech Explained",
    description: "A comprehensive investigation exploring the concept of technology, its historical evolution, and its social and scientific impacts on modern human civilization.",
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    channelName: "Tech Hub",
    uploadDate: "2026-04-01",
    duration: "3:32",
    views: "95K",
    category: "Music & Shows",
    matchScore: "89% Match",
    year: "2026",
    rating: "PG",
    language: "English"
  },
  {
    id: "358055628",
    platform: "vimeo",
    title: "Tokyo Neon Streets - Night Drone Footage",
    description: "A drone flight over Tokyo's busiest districts (Shibuya, Shinjuku, Akihabara) at midnight. Captured in anamorphic 4K with deep blues, neon pinks, and dynamic light trails.",
    thumbnail: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80",
    channelName: "CineShots",
    uploadDate: "2025-05-18",
    duration: "2:45",
    views: "620K",
    category: "Short Films & Animation",
    matchScore: "93% Match",
    year: "2025",
    rating: "G",
    language: "Japanese"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { mockVideos };
} else {
  window.mockVideos = mockVideos;
}
